### ISSUE TITLE
LUA error, making action bar unusable

### ISSUE THREAD

**Issue by hollo6** [GurliGebis/WoWAddon-AngrierWorldQuests#26]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'AngrierWorldQuests' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR1BUTTON5"]:2: in function <[string "MULTIACTIONBAR1BUTTON5"]:1>

**Comment by GurliGebis** [comment]
Thanks :)

This error is caused by something else tainting the UI, which then causes this (and other addons) to fail when they use it.
The problem with that is, whatever breaks the UI does not cause an error right then and there, but only when something else runs into it, will it fail, pointing to that addon as the cause of the problem.

If you want, you can see this one, which is the same error: #24
