### ISSUE TITLE
Refresh issue with WQ's at bottom of quest log forcing quest log to scroll up.

### ISSUE THREAD

**Issue by ghost** [GurliGebis/WoWAddon-AngrierWorldQuests#38]
Hello,

I've had this issue for a while, but it's getting progressively more annoying, hence I'm reporting the issue! :P

When the world quests are selected to be at the bottom of the quest log (instead of top as default), there is this an odd refresh (or similar) which happens, and it automatically scrolls to the top of the quest log. This happens VERY often.

Thank you so much :)

**Comment by GurliGebis** [comment]
I'll take a look at it

**Comment by GurliGebis** [comment]
@JBabbb I have been looking at it, and I have come up with the following:

It happens with the list being both at the top and at the bottom.
You have to wait a minute or so for it to happen.
It seems to be blizzard causing it to refresh, due to the `QuestLogQuests_Update` event being triggered.

It most likely is due to the list being updated, which causes the scrolling.
I have been playing around with trying to fix it, but I haven't been able to come up with a solution that works.

If anyone wants to help, the problem is when the `QuestFrame_Update` function is being called.

**Comment by GurliGebis** [comment]
Can you please try with version `v0.43.0` and see if it works now (Things have been reworked quiet a bit).
If it is still broken, please reopen.
