### ISSUE TITLE
Dream Wardens WQs don't show

### ISSUE THREAD

**Issue by Rubyurek** [GurliGebis/WoWAddon-AngrierWorldQuests#46]
Not all WQs are displayed. The "Emerald Dream" area is not listed if I deactivate the "Only show WQ for the current zone" function. When I activate the function, they are also displayed.
![1](https://github.com/GurliGebis/WoWAddon-AngrierWorldQuests/assets/42946288/1f87c185-34c8-45f1-b017-c2eb4adb80ac)
![2](https://github.com/GurliGebis/WoWAddon-AngrierWorldQuests/assets/42946288/06fc565b-9cbc-4708-8cca-192d9de1ed02)
![3](https://github.com/GurliGebis/WoWAddon-AngrierWorldQuests/assets/42946288/d9b956c6-c8e0-46d2-acac-d505d4f71d0b)
![4](https://github.com/GurliGebis/WoWAddon-AngrierWorldQuests/assets/42946288/46071865-f05a-4909-a221-106cc104be92)

**Comment by GurliGebis** [comment]
Okay, that is a strange issue.
I can reproduce it on my installation, and I have an idea on what is wrong.
It might be a few days before I can get time to fix it though.

**Comment by GurliGebis** [comment]
I found the issue - the problem is that when filtering is not set to the current zone, the `C_TaskQuest.GetQuestsForPlayerByMapID` function is called with the Dragonflight main zone id - and that doesn't return quests for neither The Emerald Dream or Zaralek Cavern.
So I have made a workaround, which solves the problem.
