### ISSUE TITLE
Map bug/conflict?

### ISSUE THREAD

**Issue by thestarsaredown** [GurliGebis/WoWAddon-AngrierWorldQuests#97]
After the 11.0.7 drop, I've noticed two issues, possibly (likely?) related

1) Despite the list itself following the filter criteria applied, the world map shows every available WQ, whether it meets the criteria or not.  Not a huge deal
2) The addon now conflicts with PetTracker, which is another addon with significant map usage (hence the possibly related).  if PetTracker is enabled, no listing of WQ is available at all (but they still show up on the map, same as in 1) )

Neither addon has updated recently, both worked fine prior to the patch on 12/17

**Comment by GurliGebis** [comment]
Hey,

1: I just tested this - if I have `Hide filtered World Quests POI icons on the world map` checked, and `Hide untracked World Quest POI icons on the world map` unchecked, and then filter on something (like pet battles), it only shows those - see screenshot below.

2: Well, I'm not really a fan of PetTracker, since the author started threatening people with DMCA takedowns, and used to pretend his addons where open source (while adding clauses that removed all the freedoms the license gave the user).
So working on compatibility with that addon is not something I will be doing (if people have patches, they are welcome to submit them) - instead, I have created another addon which does most of what PetTracker does (and is already up to date with the 11.0.7 pets, which at the moment, PetTracker isn't) - if you want, have a look at `Battle Pet Completionist`


![billede](https://github.com/user-attachments/assets/0cbc5f2a-ec5a-4f55-8886-8190713daefd)

**Comment by thestarsaredown** [comment]
I can understand your position on point 2, so leaving that aside :)

When I have the two options you indicated flagged as you do (which is my default), I get a view similar to yours if I'm looking at a continent map

If I zone into say, Azure Span, I see every quest again.  Not the worst problem to have, and obviously not an urgent fix since it's easily remedied by zooming out one tick.

I'll take a look at the other addon though

**Comment by GurliGebis** [comment]
You are indeed right - it doesn't work when you look at it from a specific zone.
I'll take a look at it - though it is getting late, so it won't be today.

Thanks for reporting the issue 😊

**Comment by Shauren** [comment]
@OP
PetTracker currently doesn't work properly on 11.0.7 and it hooks into blizzard builtin DropDownMenu
AngrierWorldQuests interacts with blizzard builtin DropdownMenu - so it gets broken by PetTracker being broken (to be clear, AngrierWorldQuests is doing the right thing here, PetTracker just breaks everyone)

**Comment by GurliGebis** [comment]
@thestarsaredown It should be solved with the changes in `11.0.7-20241222-1` - it seems like the entire filtering was broken, due to some changes Blizzard did in their `WorldQuestDataProvider.lua` provider.

Please test again and report back.

**Comment by thestarsaredown** [comment]
Confirmed.  Thank you!
Marking closed :)
